### ISSUE TITLE
wrong endpoint link

### ISSUE THREAD

**Issue by ezal** [tacoinfra/teztnets#20]
I think the suffix `/chains/main/chain_id` in the "Public RPC endpoints" URI at https://github.com/tacoinfra/teztnets/blob/b780c37cc29702fff5f809d136ca4ae0123fe324/teztnets_xyz_page/teztnet_page.md.jinja2#L11 should be removed.

**Comment by drchrispinnock** [comment]
It should not - I believe the idea of the previous maintains was that  it actually works when clicked.
