### ISSUE TITLE
clone the github wiki

### ISSUE THREAD

**Issue by craigbuckler** [tacoinfra/teztnets#7]
to here from https://github.com/oxheadalpha/teztnets/wiki

**Comment by nicolasochem** [comment]
this wiki was a preliminary version of our internal document and was copied into our internal document, do we really need it?

**Comment by craigbuckler** [comment]
It'd be good to keep it given we may eventually lose access. It may duplicate much of the internal doc, but I'd rather have that than potentially lose something. I'll look into it...

**Comment by craigbuckler** [comment]
I've cloned the Oxhead wiki.
